; $8000
con_bank_id                     = $00

; ram_btn_press                 = $8E
; ram_btn_hold                  = $91
con_btn_Right                   = $01 ; 
con_btn_Left                    = $02 ; 
con_btn_Down                    = $04 ; 
con_btn_Up                      = $08 ; 
con_btn_Start                   = $10 ; 
con_btn_Select                  = $20 ; 
con_btn_B                       = $40 ; 
con_btn_A                       = $80 ; 

con_btns_Dpad                   = con_btn_Right + con_btn_Left + con_btn_Down + con_btn_Up  ; 0F
con_btns_AB                     = con_btn_A + con_btn_B                                     ; C0
con_btns_LR                     = con_btn_Left + con_btn_Right                              ; 03



; ram_object_id                 = $0550
con_fighter_Leo                 = $00 ; 
con_fighter_Raph                = $01 ; 
con_fighter_Mike                = $02 ; 
con_fighter_Don                 = $03 ; 
con_fighter_Casey               = $04 ; 
con_fighter_Hot                 = $05 ; 
con_fighter_Shred               = $06 ; 

